FROM registry.access.redhat.com/ubi8/go-toolset

USER root

WORKDIR /addon-metadata-operator

# Cache optimization
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

ENTRYPOINT ["make"]

CMD ["check", "test", "build"]
