# vi: set ft=dockerfile:
FROM registry.ci.openshift.org/openshift/release:golang-1.16

USER root

WORKDIR /addon-metadata-operator

# Cache optimization
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN make vendor
ENTRYPOINT ["make"]

CMD ["check", "test", "build"]
